name: socketcluster_client
description: SocketCluster.io Client for Dart
version: 0.2.4
authors:
  - Paul DeMarco <paulmdemarco@gmail.com>
  - Michael Marner <michael@20papercups.net>
homepage: https://github.com/pauldemarco/socketcluster_client
environment:
  sdk: ">=2.0.0 <3.0.0"
dev_dependencies:
  test: ^1.3.0
